container:
  image: registry.gitlab.com/cryptoadvance/specter-desktop/cirrus-jammy:20220908

test_task:
  pip_script:
    - virtualenv --python=python3 .env 
    - source ./.env/bin/activate
    - pip3 install -e .
    #- python3 setup.py install
    - echo $PATH
    - coverage run -m pytest
    - coverage report
    - coverage xml
  always:
    junit_artifacts:
      path: "./testresults.xml"
      format: junit 
